#!/bin/sh

# Package
PACKAGE="settopbox"
DNAME="SettopBox"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
PATH="${INSTALL_DIR}/bin:${PATH}"
USER="${PACKAGE}"
USER_HOME="$(eval echo ~$USER)"
PID_FILE="${USER_HOME}/.config/SettopBox/settopbox.pid"
INSTALL_LOG="${INSTALL_DIR}/var/install.log"
MONO_PATH="/var/packages/Mono/target/usr/bin"
MONO="${MONO_PATH}/mono-service"
SETTOPBOXDIR="${INSTALL_DIR}/share/SettopBox/"
SETTOPBOX="${SETTOPBOXDIR}SettopBox.exe"
COMMAND="env PATH=${MONO_PATH}:${PATH} ${MONO} ${SETTOPBOX}"

start_daemon ()
{
	echo 'Start ${COMMAND}'
	${MONO} -d:${SETTOPBOXDIR} -l:${PID_FILE} ${SETTOPBOX}
	sleep 2
}

stop_daemon ()
{
	kill $(cat ${PID_FILE})
	sleep 2
}

daemon_status ()
{
	if [ -f ${PID_FILE} ]; then
		return ps -P $(cat ${PID_FILE})
	fi
	return false
}

wait_for_status ()
{
    counter=$2
    while [ ${counter} -gt 0 ]; do
        daemon_status
        [ $? -eq $1 ] && return
        let counter=counter-1
        sleep 1
    done
    return 1
}

case $1 in
    start)
        if daemon_status; then
            echo ${DNAME} is already running
        else
            echo Starting ${DNAME} ...
            start_daemon
        fi
        ;;
    stop)
        if daemon_status; then
            echo Stopping ${DNAME} ...
            stop_daemon
        else
            echo ${DNAME} is not running
        fi
        ;;
    status)       
	if daemon_status; then
            echo ${DNAME} is running
            exit 0
        else
            echo ${DNAME} is not running
            exit 1
        fi
        ;;
    log)
	echo "${INSTALL_LOG}"
        exit 0
        ;;
    *)
        exit 1
        ;;
esac
